Configuration:
  Debug: false
  StorageType: LOCAL
  Transform:
    From: LOCAL
    To: MySQL
  MySQL:
    Database: database
    Host: localhost
    Port: 3306
    Username: root
    Password: root
    SSL: false
  Arenas:
    Status:
      Waiting: "&aESPERANDO"
      Starting: "&6INICIANDO"
      Playing: "&cEN JUEGO"
      Ending: "&cTERMINANDO"
      Disabled: "&4DESACTIVADA"
    Per Arena Chat: true
    Checkpoints:
      Firework:
        Enabled: true
      Under Block: EMERALD_BLOCK
      Plate: GOLD_PLATE