Configuration:
  Debug: false
  StorageType: LOCAL # LOCAL, MySQL
  MySQL:
    Database: database
    Host: localhost
    Port: 3306
    Username: root
    Password: root
    SSL: false
  Arenas:
    Per Arena Chat: true