Configuration:
  Debug: false
  StorageType: LOCAL # LOCAL, MySQL, TRANSFORM, only use this to transform data from MySQL to LOCAL and vice versa
  Transform:
    From: LOCAL
    To: MySQL
  MySQL:
    Database: database
    Host: localhost
    Port: 3306
    Username: root
    Password: root
    SSL: false
  Arenas:
    Per Arena Chat: true
    Checkpoints:
      Firework:
        Enabled: true
      Under Block: EMERALD_BLOCK
      Plate: GOLD_PLATE